#!/usr/bin/env bash
# custom HTTP header

sudo apt update
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/http {/&\n\tadd_header X-Served-By $HOSTNAME;/' /etc/nginx/nginx.conf
sudo service nginx restart
